<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<RootNamespace>Cannery.Aspects.Components</RootNamespace>
		<AssemblyName>Cannery.Aspects.Components</AssemblyName>
		<Version>1.0.0</Version>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="wwwroot\**" />
	  <Content Remove="wwwroot\**" />
	  <EmbeddedResource Remove="wwwroot\**" />
	  <None Remove="wwwroot\**" />
	</ItemGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Goodtocode.SecuredHttpClient" Version="1.1.7" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.2" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.2" />		
		<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.13.2" />
		<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Emoji" Version="4.13.2" />
		<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.13.2" />
		<PackageReference Include="Microsoft.Identity.Web" Version="4.3.0" />
		<PackageReference Include="Microsoft.Identity.Web.DownstreamApi" Version="4.3.0" />

	</ItemGroup>
</Project>
