<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>		
		<RootNamespace>Goodtocode.SemanticKernel.Core.Domain</RootNamespace>
		<AssemblyName>Goodtocode.SemanticKernel.Core.Domain</AssemblyName>
		<Version>1.0.0</Version>
		<TargetFramework>net10.0</TargetFramework>
		<IsPackable>false</IsPackable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="CSharpFunctionalExtensions" Version="3.6.0" />
		<PackageReference Include="Goodtocode.Domain" Version="1.1.6" />
	</ItemGroup>
</Project>
