<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<RootNamespace>Goodtocode.SemanticKernel.Presentation.Blazor</RootNamespace>
		<AssemblyName>Goodtocode.SemanticKernel.Presentation.Blazor</AssemblyName>
		<Version>1.0.0</Version>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>c2325466-9b0d-494a-984a-11ad18457d3f</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Identity" Version="1.17.1" />
		<PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" Version="1.4.0" />
		<PackageReference Include="Azure.Monitor.OpenTelemetry.Exporter" Version="1.5.0" />
		<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.23.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.2.0" />
		<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.13.2" />		
		<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Emoji" Version="4.13.2" />		
		<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.13.2" />
		<PackageReference Include="Microsoft.Identity.Web" Version="4.3.0" />
		<PackageReference Include="Microsoft.Identity.Web.DownstreamApi" Version="4.3.0" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.15.0" />		
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Aspects.Components\Aspects.Components.csproj" />
	</ItemGroup>

</Project>
