<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>		
		<RootNamespace>Goodtocode.SemanticKernel.Core.Application</RootNamespace>
		<AssemblyName>Goodtocode.SemanticKernel.Core.Application</AssemblyName>
		<Version>1.0.0</Version>
		<TargetFramework>net10.0</TargetFramework>
		<IsPackable>false</IsPackable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>		
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Goodtocode.Mediator" Version="1.1.5" />
		<PackageReference Include="Goodtocode.Validation" Version="1.1.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2" />
		<PackageReference Include="Microsoft.SemanticKernel.Abstractions" Version="1.69.0" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Core.Domain\Core.Domain.csproj" />
	</ItemGroup>
</Project>